# Generated by Django 6.0.3 on 2026-03-31 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0005_wishlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'product')},
        ),
    ]
